credentials:
  usernames:
    user1:
      name: Alice
      password: '$2b$12$eP0JzqElzKbcfL5lxL27/.E7mAq6YQJ3YvNNgM3OVLfW03YkU7OOS'  # pass123
    user2:
      name: Bob
      password: '$2b$12$NcOef9iFYw4gFbZZuD04aeEOaECAnYAfU88U62yP.Su5FF/cjxuh6'  # mypassword

cookie:
  name: freshness_cookie
  key: some_random_key
  expiry_days: 7
