credentials:
  usernames:
    jdoe:
      email: jdoe@example.com
      name: John Doe
      password: '$2b$12$KIXoa2BPa.CckBvR1fsYLOe1eU3a6PC6o/I7jqStw5UMYOyn3xM2m'  # hashed password

cookie:
  name: freshness_cookie
  key: some_secret_key
  expiry_days: 7


